server:
  domain: user
  version: 1.0
  jwtSecret: todolist
  grpcAddress: "127.0.0.1:10001"

mysql:
  driverName: mysql
  host: cloud.io
  port: 3306
  database: grpc_todo_list
  username: root
  password: root
  charset: utf8mb4

etcd:
  endpoints:
  - cloud.io:2379

redis:
  address: cloud.io:6379
  password: